### ISSUE TITLE
postName strings have encoded special characters

### ISSUE THREAD

**Issue by bruceblay** [jordanleven/force-refresh#25]
# postName strings have encoded special characters

### Which area are you seeing an issue with
Admin - Post editor

### What type of issue are you reporting

- [x ] Incorrect/Unexpected behavior
- [ ] Data loss or security issue
- [ ] Plugin crash
- [ ] Plugin slow or unresponsive
- [ ] Feature request or enhancement

## Current Behavior
Encoded characters in the postName causes the refresh button to overflow outside the meta box.

## Steps to Reproduce
  
1. Create a post with a hyphen or another special character in the name.
2. Check the Force Refresh meta box on the post edit page.

![encoded-characters](https://user-images.githubusercontent.com/1952514/97365852-608c1c00-1874-11eb-8f54-c48a71c36e80.png)

Looks like Vue doesn't like my postNames.  PR incoming

**Comment by jordanleven** [comment]
@bruceblay  - This issue has been addressed in Force Refresh 2.2. I'm going to close this out for now, but feel free to revisit this thread if you continue to have issues.
