### ISSUE TITLE
Add a shortcode for the Refresh Button

### ISSUE THREAD

**Issue by Curiousnoes** [jordanleven/force-refresh#395]
### What type of issue are you reporting

- [ ] Incorrect/Unexpected behavior
- [ ] Data loss or security issue
- [ ] Plugin crash
- [ ] Plugin slow or unresponsive
- [X] Feature request or enhancement

## Current Behavior

It works as expected, great plugin!

## Feature Request
Can you add a shortcode for the refresh button so I can set it on a specific page so I dont need to go to my dashboard?
Other than that it is a great plugin. Works as expected.

**Comment by jordanleven** [comment]
Hey @Curiousnoes  - can you add some more details about what you're looking for? You want an Admin-only shortcode to show up on a page to request a force refresh when viewing it as an end-user?

**Comment by jordanleven** [comment]
Didn't hear back from issue author. Closing for now.

**Comment by Curiousnoes** [comment]
I am so sorry for the delay!
What I am looking for is a shortcode or something for the refresh button.
So it is not only in the admin menu, but it can be placed on any page. Not necessarily for admin only.

Why?
I made a sort of game, the game leader can lock pages (by boolean) and then refresh the page so the changes become visable.
Now they have to go to the admin menu.

With the shortcode, I can add the button with the rest of the buttons for my plugin.

Again, I am so sorry for my late reaction.
The project was on hold for a few months and now we are going to play it, and it came back to me about my request to you.
