### ISSUE TITLE
allow longer refresh time

### ISSUE THREAD

**Issue by dsmithersvv** [jordanleven/force-refresh#408]
### What type of issue are you reporting

- [ ] Incorrect/Unexpected behavior
- [ ] Data loss or security issue
- [ ] Plugin crash
- [ ] Plugin slow or unresponsive
- [x] Feature request or enhancement

## Current Behavior
Currently, the longest time I can set for refreshes is 3 minutes.  We have enough users logged onto our site concurrently that the calls from the browser back to the server to see if the site should refresh is overloading our site.  Could you add other options, maybe out to a half hour?

**Comment by jordanleven** [comment]
Hey @dsmithersvv  - this feature is being added to Force Refresh and will be made available in the next minor release. Instead of adding support for additional longer options, Force Refresh will allow users to set a customized refresh interval between 30 seconds and four hours.
